name: Test Dependency Graph Features

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"

jobs:
  test-dep-graph-features:
    name: Test Dependency Graph Features

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run PURL Submission Action
        uses: ./purl-submission-action
        with:
          purls: |-
            pkg:gem/ruby-advisory-db-check@0.12.4
            pkg:maven/org.apache.xmlgraphics/batik-anim@1.9.1
            pkg:maven/org.apache.log4j/log4j@1.0.4

      - name: Run Dependency Review
        uses: ./dependency-review-action
